"""init

Revision ID: 677d7fd8b060
Revises: 
Create Date: 2021-05-09 16:16:36.123722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677d7fd8b060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('buy_link', sa.String(), nullable=True),
    sa.Column('compleated', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Integer(), nullable=True),
    sa.Column('target_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_type'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_tracker')
    op.drop_table('items')
    # ### end Alembic commands ###
