"""Added position in items table

Revision ID: 9c3fcb629bf8
Revises: afa48e762ae3
Create Date: 2021-02-24 11:30:00.459118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3fcb629bf8'
down_revision = 'afa48e762ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'position')
    # ### end Alembic commands ###
