"""Added all tables

Revision ID: afa48e762ae3
Revises: 
Create Date: 2021-02-23 23:52:26.029580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa48e762ae3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('rebuy_link', sa.String(), nullable=True),
    sa.Column('compleated', sa.Boolean(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_stock')
    op.drop_table('current_stock')
    op.drop_table('items')
    # ### end Alembic commands ###
