"""renamed rebuy_link to buy link in table items

Revision ID: c4d353fd8b80
Revises: 9c3fcb629bf8
Create Date: 2021-02-24 12:25:45.901788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d353fd8b80'
down_revision = '9c3fcb629bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('buy_link', sa.String(), nullable=True))
    op.drop_column('items', 'rebuy_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('rebuy_link', sa.VARCHAR(), nullable=True))
    op.drop_column('items', 'buy_link')
    # ### end Alembic commands ###
